version: '3.8'
services:
  mydb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=board
    ports:
      - "3400:3306"

  spring-test:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    # ~에 의존하고 있으니. 이거 후 실행해라!
    depends_on:
      - mydb
    restart: on-failure:10
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mydb:3306/board #네트워크 내부의 포트

# 실행법 : docker-compose up -d
# 멈춤 및 삭제 : docker-compose down